name: Black Code Formatter

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install pre-commit and dependencies
        run: |
          pip install pre-commit black

      - name: Run pre-commit hooks
        run: pre-commit run --all-files --hook-stage=manual --verbose

      - name: Check code formatting with Black
        run: black --check --line-length=120 .
