name: Black Code Formatter

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Create Python venv
        run: python -m venv venv

      - name: Activate Python venv
        run: source venv/bin/activate

      - name: Install pre-commit, black, and Jupyter dependencies
        run: |
          source venv/bin/activate
          pip install pre-commit black black[jupyter]

      - name: Run pre-commit hooks
        run: |
          source venv/bin/activate
          pre-commit run --all-files --verbose

      - name: Check code formatting with Black
        run: |
          source venv/bin/activate
          black --check --line-length=120 .
