name: Black Code Formatter

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: float64"3.8"

      - name: Install dependencies
        run: |
          pip install black

      - name: Check code formatting
        run: black --check .
